name: 'Check reminders'

on:
  schedule:
    - cron: '*/15 * * * *'  # At the start of every hour
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Check reminders and notify
        uses: agrc/reminder-action@v1
