name: 'Create reminders'

on:
  issue_comment:
    types: [created, edited]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Check comments and create reminders
        uses: agrc/create-reminder-action@v1
