name: Tests All

on:
  pull_request:

permissions:
  contents: read

jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    name: Build Matrix based on Supported Python Versions
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: set-matrix
        run: |
          python_versions=$(sed -e 's/^[ \t]*//' setup.cfg | grep -E 'Programming Language :: Python :: [0-9]+\.[0-9]+' | cut -d' ' -f6 | sort -u -V)
          echo "Supported Python versions: $python_versions"
