name: Tests All

on:
  pull_request:

permissions:
  contents: read

jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      python_versions_output: ${{ steps.set-matrix.outputs.python_versions }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: set-matrix
        run: |
          python_versions=$(for i in `sed -e 's/^[ \t]*//' setup.cfg | grep -E 'Programming Language :: Python :: [0-9]+\.[0-9]+' | cut -d' ' -f6 | sort -u -V`; do echo -n "'$i', "; done; echo \'3.12\')
          echo "python_versions="[$python_versions]" >> "$GITHUB_OUTPUT"
          echo "Supported Python versions: $python_versions"
  build-n-test:
    runs-on: ubuntu-latest
    needs: matrix_prep
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - name: Set up Python and Build
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
        - run: echo ${{fromJson(needs.matrix_prep.outputs.python_versions_output)}}
