name: Tests All

on:
  pull_request:

permissions:
  contents: read

jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      python_versions: ${{ steps.set-matrix.outputs.python_versions }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - id: set-matrix
      run: |
        python_versions=$(for i in `sed -e 's/^[ \t]*//' setup.cfg | grep -E 'Programming Language :: Python :: [0-9]+\.[0-9]+' | cut -d' ' -f6 | sort -u -V`; do echo -n "\"$i\", "; done; echo \"3.12\")
        echo "Supported Python versions: $python_versions"
        echo "python_versions=$python_versions" >> $GITHUB_OUTPUT

  build-n-test:
    needs: matrix_prep
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"] # [${{ steps.set-matrix.outputs.python_versions }}]
    steps:
    - name: Set up Python and Build
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - run: echo "Hello ${{ matrix.python-version }} ${{ steps.set-matrix.outputs.python_versions }}"
